CXX = g++
CXXFLAGS = -std=c++11

all: fifo fifo_2 sjf sjf_2 srtf srtf_2 rr rr_2

fifo: fifo.cpp
	$(CXX) $(CXXFLAGS) -o fifo fifo.cpp

fifo_2: fifo_2.cpp
	$(CXX) $(CXXFLAGS) -o fifo_2 fifo_2.cpp

sjf: sjf.cpp
	$(CXX) $(CXXFLAGS) -o sjf sjf.cpp

sjf_2: sjf_2.cpp
	$(CXX) $(CXXFLAGS) -o sjf_2 sjf_2.cpp

srtf: srtf.cpp
	$(CXX) $(CXXFLAGS) -o srtf srtf.cpp

srtf_2: srtf_2.cpp
	$(CXX) $(CXXFLAGS) -o srtf_2 srtf_2.cpp

rr: rr.cpp
	$(CXX) $(CXXFLAGS) -o rr rr.cpp

rr_2: rr_2.cpp
	$(CXX) $(CXXFLAGS) -o rr_2 rr_2.cpp

clean:
	rm -f fifo fifo_2 sjf sjf_2 srtf srtf_2 rr rr_2

